_registry_: "structure_module"
_class_: "KFoldECSI"

# ECSI preconditioning
sigma_data: 16.0
sigma_data_end: 27.0
cov_xy: 175.0

# ECSI coefficients
time_min: 1e-8
time_max: 0.9999
gamma_max: 24.0
gamma_power: 1.0
eta: 1.0

# Inference time schedule
align_x_0_hat_to_x_t: true
sampler_mode: ode
sampler_ode_type: si
sampler_step_scale: 1.0
sampler_switch_gamma: null
sampler_after_switch_mode: ode
sampler_after_switch_ode_type: si
churn_factor: 0.1
churn_end_time: 0.5
churn_step_fraction: 0.4
churn_step_power: 1.0
ode_step_power: 2.0

# Training time schedule
train_time_schedule: logistic
train_time_schedule_params: [-2.15, 2.25]
