[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kfold"
version = "0.2.0"
description = "K-Fold"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
dependencies = [
  # core dependencies
  "torch",
  "numpy",
  # additional dependencies
  "tqdm",
  "scipy",
  "omegaconf",
  "huggingface-hub",
  "rdkit",
  "einops",
  "gemmi",
  "zstandard",
]

[project.optional-dependencies]
cuequiv = [
  "torch>=2.7.0",
  "cuequivariance_torch>=0.6.0",
  "cuequivariance_ops_cu12>=0.6.0",
  "cuequivariance_ops_torch_cu12>=0.6.0",
]
dev = ["pre-commit", "pytest"]
train = [
  'lightning', # for training loop
  'wandb', # for experiment tracking
  'lmdb', # for training dataset storage
  'msgpack', # for data serialization
  "numba",
  'bioprior @ git+https://github.com/SeonghwanSeo/bio-prior.git@v0.1.2',
]
preprocess = [
  'pdbeccdutils', # for ccd data handling
]
