_registry_: "trunk"
_class_: "Boltz1PairformerTrunk"
channel_s: 384
channel_z: 128
num_blocks: 48
num_heads: 16
dropout: 0.25
pairwise_head_width: 32
pairwise_num_heads: 4
use_msa: False
use_template: False
