_registry_: "trunk"
_class_: "PairmixerformerTrunk"
channel_s: 384
channel_z: 128
num_blocks: 48
pairmixer_blocks: 42
dropout: 0.25
use_msa: False
use_template: False
use_cuequiv_kernels: True
blocks_per_ckpt: 1
# following 2 are parameters for pairformer
num_heads_attn: 16
num_heads_tri_attn: 4
