"""Create a heuristic single-stranded DNA helix PDB for visual inspection.

Example
-------
python tests/create_dna_helix.py --sequence ACGTACGT --out tmp/dna_helix.pdb
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

import kfold.constants as C
from kfold.data.utils.dna_utils import (
    DNA_HELIX_AXIS_OFFSET,
    DNA_HELIX_CONFORMER_ROTATION,
    DNA_HELIX_RISE,
    DNA_HELIX_TWIST_DEGREES,
    build_dna_single_helix,
)

DNA_BASE_TO_RESIDUE = {
    "A": "DA",
    "G": "DG",
    "C": "DC",
    "T": "DT",
    "N": "DN",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a heuristic single-stranded DNA helix PDB."
    )
    parser.add_argument(
        "--sequence",
        required=True,
        help="DNA sequence using A/C/G/T/N. Whitespace is ignored.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("tmp/dna_helix.pdb"),
        help="Output PDB path.",
    )
    parser.add_argument(
        "--chain-id",
        default="A",
        help="Single-character PDB chain ID.",
    )
    parser.add_argument(
        "--rise",
        type=float,
        default=DNA_HELIX_RISE,
        help="Helical rise per residue in Angstrom.",
    )
    parser.add_argument(
        "--twist-degrees",
        type=float,
        default=DNA_HELIX_TWIST_DEGREES,
        help="Right-handed twist per residue in degrees.",
    )
    parser.add_argument(
        "--no-center",
        action="store_true",
        help="Keep the generated helix in the raw helical coordinate frame.",
    )
    parser.add_argument(
        "--axis-offset",
        type=float,
        nargs=3,
        default=DNA_HELIX_AXIS_OFFSET,
        metavar=("X", "Y", "Z"),
        help="Local-frame offset from the nucleotide conformer to the helix axis.",
    )
    parser.add_argument(
        "--conformer-rotation",
        type=float,
        nargs=3,
        default=DNA_HELIX_CONFORMER_ROTATION,
        metavar=("RX", "RY", "RZ"),
        help="Rotation vector in radians applied before helix placement.",
    )
    return parser.parse_args()


def normalize_sequence(sequence: str) -> str:
    sequence = "".join(sequence.split()).upper()
    invalid = sorted(set(sequence) - set(DNA_BASE_TO_RESIDUE))
    if not sequence:
        raise ValueError("DNA sequence is empty.")
    if invalid:
        raise ValueError(f"Unsupported DNA base(s): {', '.join(invalid)}")
    return sequence


def sequence_to_residue_names(sequence: str) -> list[str]:
    return [DNA_BASE_TO_RESIDUE[base] for base in sequence]


def residue_atom_names(residue_names: list[str]) -> list[list[str]]:
    return [
        [atom.value for atom in C.atom.RESIDUE_ATOMS[C.ResidueName[name]]]
        for name in residue_names
    ]


def infer_element(atom_name: str) -> str:
    for char in atom_name:
        if char.isalpha():
            return char.upper()
    return ""


def write_pdb(
    path: Path,
    residue_names: list[str],
    atom_names_by_residue: list[list[str]],
    coords: np.ndarray,
    *,
    chain_id: str,
) -> None:
    if len(chain_id) != 1:
        raise ValueError("PDB chain ID must be a single character.")

    path.parent.mkdir(parents=True, exist_ok=True)
    serial = 1
    coord_i = 0
    with path.open("w") as handle:
        handle.write("REMARK Generated by tests/create_dna_helix.py\n")
        handle.write("REMARK Heuristic right-handed single-stranded DNA helix\n")
        for res_i, (res_name, atom_names) in enumerate(
            zip(residue_names, atom_names_by_residue, strict=True),
            start=1,
        ):
            for atom_name in atom_names:
                x, y, z = coords[coord_i]
                element = infer_element(atom_name)
                handle.write(
                    f"ATOM  {serial:5d} {atom_name:^4s} {res_name:>3s} "
                    f"{chain_id}{res_i:4d}    "
                    f"{x:8.3f}{y:8.3f}{z:8.3f}"
                    f"{1.00:6.2f}{0.00:6.2f}          {element:>2s}\n"
                )
                serial += 1
                coord_i += 1
        handle.write("TER\nEND\n")


def main() -> None:
    args = parse_args()
    sequence = normalize_sequence(args.sequence)
    residue_names = sequence_to_residue_names(sequence)
    atom_names_by_residue = residue_atom_names(residue_names)
    coords = build_dna_single_helix(
        atom_names_by_residue,
        residue_names=residue_names,
        rise=args.rise,
        twist_degrees=args.twist_degrees,
        axis_offset=tuple(args.axis_offset),
        conformer_rotation=tuple(args.conformer_rotation),
        center=not args.no_center,
    )
    write_pdb(
        args.out,
        residue_names,
        atom_names_by_residue,
        coords,
        chain_id=args.chain_id,
    )
    print(f"Wrote {len(sequence)} nt / {coords.shape[0]} atoms to {args.out.resolve()}")


if __name__ == "__main__":
    main()
