from pathlib import Path

import pytorch_lightning as pl
import torch

from kfold.config import load_config
from kfold.data.model_input import FoldingInput
from kfold.data.structure import TokenizedStructure
from kfold.model.models.boltz1 import Boltz1
from kfold.training.folding.dataset.datamodule import TrainingDataModule

TEST_CONFIG_PATH = Path("./configs/train-boltz1.yaml")
BOLTZ_FEATURE_PATH = Path("../boltz/tmp/")
SAVE_STRUCTURE_PATH = Path("./tmp/boltz-validate/")
SAVE_STRUCTURE_PATH.mkdir(parents=True, exist_ok=True)

if __name__ == "__main__":
    # Turn off gradient
    torch.set_grad_enabled(False)
    pl.seed_everything(42)

    # Load Config
    global_config = load_config(TEST_CONFIG_PATH)

    # Modify config for testing
    global_config.model.load_weight = True
    global_config.model.freeze_weight = True
    global_config.train.data.featurization_args.augment_ref_pos = False

    # === Load Model === #
    model = Boltz1(global_config)
    model = model.eval()
    model = model.cuda()

    # === Get data loader === #
    data_module = TrainingDataModule(global_config.train.data)
    data_module.setup("validate")

    # Only use keys with Boltz features
    val_pdb_ids = [
        f.name.replace("_features.pt", "")
        for f in BOLTZ_FEATURE_PATH.glob("*_features.pt")
    ]
    print(val_pdb_ids)
    data_module._val_ds.records = [
        r for r in data_module._val_ds.records if r.id in val_pdb_ids
    ]

    dataloader = data_module.val_dataloader()

    # === Get Embeddings and Save === #

    f_input: FoldingInput
    for f_input, full_dict_list in dataloader:
        assert f_input.batch_size == 1

        full_dict = full_dict_list[0]
        pdb_id: str = full_dict["id"]
        struct: TokenizedStructure = full_dict["structure"]
        print(
            f"Loaded sample {pdb_id}: {struct.num_chains} chains and "
            f"{struct.num_residues} residues."
        )

        # Move to GPU
        f_input = f_input.to(device="cuda")

        # === Check Embeddings === #
        s_inputs, s_init, z_init = model.input_embedder(f_input)
        s_trunk, z_trunk = model.trunk(
            s_inputs,
            s_init,
            z_init,
            f_input,
            num_cycles=4,
        )
        p_distogram = model.distogram_head(z_trunk)

        # Sample structures
        sample_coords = model.structure_module.sample_structure(
            f_input,
            s_inputs,
            s_trunk,
            z_trunk,
            num_steps=200,
            num_diffusion_samples=5,
        )["sample_coordinates"][0]  # (Nsamples, N, 3)

        # Remove paddings and move to cpu
        n_tokens = struct.num_tokens
        features = {
            "s_inputs": s_inputs.cpu()[0, :n_tokens],
            "s_init": s_init.cpu()[0, :n_tokens],
            "z_init": z_init.cpu()[0, :n_tokens, :n_tokens],
            "s_trunk": s_trunk.cpu()[0, :n_tokens],
            "z_trunk": z_trunk.cpu()[0, :n_tokens, :n_tokens],
            "p_distogram": p_distogram.cpu()[0, :n_tokens, :n_tokens],
        }
        sample_coords = sample_coords.cpu()

        # Compare with Boltz features
        feature_path = BOLTZ_FEATURE_PATH / f"{pdb_id}_features.pt"
        with open(feature_path, "rb") as f:
            boltz_features = torch.load(f)
        all_close = True
        for key in features:
            if not torch.allclose(
                features[key], boltz_features[key], rtol=1e-3, atol=1e-4
            ):
                diff = torch.abs(features[key] - boltz_features[key]).max()
                print(f"Feature {key} does not match for {pdb_id}, max diff: {diff}")
                all_close = False
        if all_close:
            print(f"All features match for {pdb_id}!")

        # === Save Structures === #
        # Save structures generated by KFold
        kfold_struct = struct.replace_atom_coords(sample_coords.numpy())
        try:
            for i in range(sample_coords.shape[0]):
                save_path = SAVE_STRUCTURE_PATH / f"{pdb_id}-kfold-{i}.pdb"
                kfold_struct.to_pdb(save_path, i)
        except Exception as e:
            print(f"Failed to save kfold structure for {pdb_id}: {e}")
            continue

        # Save structures generated by Boltz
        coords = boltz_features["sample_coords"].numpy()
        boltz_struct = struct.replace_atom_coords(coords)
        try:
            for i in range(coords.shape[0]):
                save_path = SAVE_STRUCTURE_PATH / f"{pdb_id}-boltz-{i}.pdb"
                boltz_struct.to_pdb(save_path, i)
        except Exception as e:
            print(f"Failed to save boltz structure for {pdb_id}: {e}")
            continue
