_yaml_: "full.yaml"

data:
  ccd_path: /cache/wykim_lab/kfold_data/v260701_af3/ccd-train.pkl
  data_root: /cache/wykim_lab/kfold_data/v260701_af3/dataset/
  train_datasets:
    # RCSB PDB (60%)
    - _yaml_: "../dataset/rcsb-train.yaml"
      name: rcsb-train
      weight: 0.600

    # Disordered PDB datasets (1%)
    - _yaml_: "../dataset/disordered_pdb.yaml"
      name: disordered_pdb
      weight: 0.010

    # Protein Monomer (35%)
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AF2-MGnify-long # 16M
      weight: 0.300
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AF2-MGnify-short # 400k
      weight: 0.001

    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AFDB-long # 3M
      weight: 0.045
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AFDB-short # 3M
      weight: 0.004

    # RNA Monomer (1%)
    - _yaml_: "../dataset/distill-rna-monomer.yaml"
      name: Rfam
      weight: 0.010

    # Protein-DNA (2%) - not yet
    # - _yaml_: "../dataset/distill-complex.yaml"
    #   name: JASPAR
    #   weight: 0.020

    # Protein-ligand, TPD (2%)
    - _yaml_: "../dataset/distill-interface.yaml"
      name: TPD
      weight: 0.020

  val_datasets:
    - _yaml_: "../dataset/rcsb-val.yaml"
      name: rcsb-val
