_registry_: "structure_module"
_class_: "Boltz1SampleDiffusion"
num_steps: 200
sigma_min: 0.0004
sigma_max: 160.0
sigma_data: 16.0
rho: 7
P_mean: -1.2
P_std: 1.5
gamma_0: 0.8
gamma_min: 1.0
noise_scale: 1.003
step_scale: 1.5
coordinate_augmentation: True
synchronize_sigmas: True
