# Based on Protenix-mini configuration
#
_yaml_: "af3.yaml"

trunk:
  num_blocks: 16

score_model:
  atom_encoder_blocks: 1
  token_transformer_blocks: 8
  atom_decoder_blocks: 1

structure_module:
  num_steps: 5
