# Based on af3-mini.yaml, but with KFoldBridgeDiffusion structure module
# Cannot inherit from af3.yaml because structure_module._yaml_ is in struct mode
_registry_: "main_module"
_class_: Boltz1Pretrained

input_embedder:
  _yaml_: "module/input_embedder/boltz1.yaml"

trunk:
  _yaml_: "module/trunk/boltz1.yaml"

structure_module:
  _yaml_: "module/structure_module/ddbm.yaml"

score_model:
  _yaml_: "module/score_model/af3.yaml"

distogram_head:
  _yaml_: "module/distogram_head/boltz1.yaml"
