# === Model Configuration === #
_registry_: "main_module"
_class_: KFold

# kernel settings
kernel_cuequivariance: true

# Module configurations
input_embedder:
  _yaml_: "module/input_embedder.yaml"

sequence_encoder:
  _yaml_: "module/sequence_encoder.yaml"

structure_encoder:
  _yaml_: "module/structure_encoder.yaml"

trunk:
  _yaml_: "module/trunk.yaml"

score_model:
  _yaml_: "module/score_model.yaml"
  channel_coords: 6

diffusion_head:
  _yaml_: "module/ecsi.yaml"

distogram_head:
  _yaml_: "module/distogram_head.yaml"

confidence_head:
  _yaml_: "module/confidence_head.yaml"

# Training preconditioning
diffusion_conditioning_drop_rate: 0.2
confidence_conditioning_drop_rate: 0.2
