# === Model Configuration === #
_registry_: "main_module"
_class_: KFold

# kernel settings
kernel_cuequivariance: true

# Module configurations
channel_s: 384
channel_z: 128
channel_plm: 768

input_embedder:
  _yaml_: "module/input_embedder.yaml"

protein_sequence_encoder:
  _yaml_: "module/protein_sequence_encoder.yaml"

protein_structure_encoder:
  _yaml_: "module/protein_structure_encoder.yaml"

rna_sequence_encoder:
  _yaml_: "module/rna_sequence_encoder.yaml"

plm_module:
  num_heads_attn: 16
  num_heads_tri_attn: 4
  num_blocks: 4
  dropout_plm: 0.15
  dropout_z: 0.25
  blocks_per_ckpt: null

pairformer:
  num_heads_attn: 16
  num_heads_tri_attn: 4
  num_blocks: 48
  dropout: 0.25
  blocks_per_ckpt: null

score_model:
  _yaml_: "module/score_model.yaml"

diffusion_head:
  _yaml_: "module/edm.yaml"

distogram_head:
  _yaml_: "module/prediction_head.yaml"

confidence_head:
  _yaml_: "module/prediction_head.yaml"

# Training preconditioning
diffusion_conditioning_drop_rate: 0.2
confidence_conditioning_drop_rate: 0.2
