# === Model Configuration === #
_registry_: "main_module"
_class_: KFold

# kernel settings
kernel:
  cuequivariance: true

# compilation settings
compile_trunk: false
compile_score_model: false
compile_mode: "default"

# Module configurations
input_embedder:
  _yaml_: "module/input_embedder/kfold.yaml"

trunk:
  _yaml_: "module/trunk/kfold.yaml"

structure_module:
  _yaml_: "module/structure_module/af3.yaml"

score_model:
  _yaml_: "module/score_model/af3.yaml"

distogram_head:
  _yaml_: "module/distogram_head/af3.yaml"

interaction_head: null
