# Default dataset configuration.
name: ???

# Data paths
data_path: <DATA_PATH_PLACEHOLDER>
manifest_path: null # optionally provide a custom manifest path
seed: null # should be null for data augmentation

apo_init:
  prob_perturbation: 0.0
  use_holo_if_apo_unavailable: false
  perturbation: null
