# RCSB training dataset configuration.
name: ???

# Data paths
data_path: <DATA_PATH_PLACEHOLDER>
manifest_path: null # optionally provide a custom manifest path
seed: null # should be null for data augmentation
is_protein_monomer_distillation: false # whether this dataset is for protein monomer distillation

apo_init:
  use_random_augmentation: true
  use_residue_permutation: false
  prob_perturbation: 0.95
  use_cached_conformer_only: true
  use_holo_if_apo_unavailable: false
  protein_perturbation: null
  ligand_perturbation: null

prior_sampler:
  num_samples: 0
  use_random_augmentation: true
  use_chain_com_sampling: false
  use_ot_permutation: false
  translation_scale: 1.0 # Angstroms
  # missing atom filling settings
  relaxation:
    num_steps: 64
    res_r: 4.0
    bond_r: 2.0
