_yaml_: "default-train.yaml"

name: synthetic
type: "distillation"

sampler:
  _registry_: "data_sampler"
  _class_: ClusterSampler
  beta_chain: 0.0
  beta_interface: 1.0
  allow_redundant: false

cropper:
  _registry_: "data_cropper"
  _class_: AlphaFold3Cropper
  w_contiguous: 0.0
  w_spatial: 0.0
  w_spatial_interface: 1.0
