_yaml_: "default-train.yaml"

name: AFDB-homodimer
type: "homodimer-distillation"
prob_drop_apo: 1.0
prob_drop_struct_token: 1.0

sampler: null

cropper:
  _registry_: "data_cropper"
  _class_: AlphaFold3Cropper
  w_contiguous: 0.2
  w_spatial: 0.4
  w_spatial_interface: 0.4

prob_perturbation: 1.0
apo_perturb:
  bioprior:
    max_steps: 20
