_yaml_: "default-train.yaml"

name: af2
type: "protein-monomer-distillation"
prob_drop_apo: 1.0
prob_drop_struct_token: 1.0

sampler: null

cropper:
  _registry_: "data_cropper"
  _class_: AlphaFold3Cropper
  w_contiguous: 0.25
  w_spatial: 0.75
  w_spatial_interface: 0.0

prob_perturbation: 1.0
apo_perturb:
  prob_rieprody: 0.0
  bioprior:
    max_steps: 10 # Maximum random walk steps
