_yaml_: "default-train.yaml"

name: ???
type: "distillation"

sampler: null

cropper:
  _registry_: "data_cropper"
  _class_: AlphaFold3Cropper
  w_contiguous: 0.0
  w_spatial: 0.0
  w_spatial_interface: 1.0
