# RCSB training dataset configuration.
_yaml_: "default-train.yaml"

name: natural-ab
weight: 0.02

# Data paths
data_path: <DATA_PATH_PLACEHOLDER>
seed: null # should be null for data augmentation

sampler:
  _registry_: "data_sampler"
  _class_: UniformSampler
  level: "complex"

cropper:
  _registry_: "data_cropper"
  _class_: MultiAnchorCropper
  max_anchors: 2
  w_contiguous: 0.0
  w_spatial: 0.0
  w_spatial_interface: 1.0

apo_init:
  # no ligand
  ligand_perturbation: null
