# Synthetic dataset configuration from ENCORE.
_yaml_: "default-train.yaml"

name: protac_db
weight: 0.0045

# Data paths
data_path: <DATA_PATH_PLACEHOLDER>
seed: null # should be null for data augmentation

sampler: null

cropper:
  _registry_: "data_cropper"
  _class_: AlphaFold3Cropper
  w_contiguous: 0.0
  w_spatial: 0.0
  w_spatial_interface: 1.0
