# RCSB training dataset configuration.
_yaml_: "rcsb-train.yaml"

cropper:
  _registry_: "data_cropper"
  _class_: MultiAnchorCropper
  max_anchors: 2
  w_contiguous: 0.2
  w_spatial: 0.4
  w_spatial_interface: 0.4
