"""Lightweight affinity cache schema identifiers safe for CPU-only tooling."""

AFFINITY_CACHE_SCHEMA_FULL_CROSS_V1 = "affinity_full_cross_v1"
AFFINITY_CACHE_SCHEMA_FULL_CROSS_POCKET_V2 = "affinity_full_cross_pocket_v2"
AFFINITY_CACHE_SCHEMA_POCKET_CROPPED_V1 = "affinity_pocket_cropped_v1"
AFFINITY_CACHE_SCHEMA_POCKET80K_TARGET_COMPACT_V1 = (
    "affinity_pocket80k_target_consensus_100_v1"
)
AFFINITY_CACHE_SCHEMA_POCKET80K_TARGET_DIRECT_V2 = (
    "affinity_pocket80k_target_consensus_100_v2"
)
AFFINITY_CACHE_SCHEMA_POCKET80K_QUERY_ADAPTIVE_80_20_V1 = (
    "affinity_pocket80k_query_adaptive_80_20_v1"
)
AFFINITY_DISTOGRAM_CROP_CONTRACT_V2 = "affinity_distogram_crop_v2"
AFFINITY_DISTOGRAM_TARGET_CONSENSUS_CONTRACT_V1 = "affinity_distogram_target_consensus_v1"
AFFINITY_FULL_CROSS_SCHEMAS = frozenset(
    (
        AFFINITY_CACHE_SCHEMA_FULL_CROSS_V1,
        AFFINITY_CACHE_SCHEMA_FULL_CROSS_POCKET_V2,
    )
)
AFFINITY_COMPACT_SCHEMAS = frozenset(
    (
        AFFINITY_CACHE_SCHEMA_POCKET_CROPPED_V1,
        AFFINITY_CACHE_SCHEMA_POCKET80K_TARGET_COMPACT_V1,
        AFFINITY_CACHE_SCHEMA_POCKET80K_TARGET_DIRECT_V2,
        AFFINITY_CACHE_SCHEMA_POCKET80K_QUERY_ADAPTIVE_80_20_V1,
    )
)
AFFINITY_CACHE_SCHEMAS = AFFINITY_FULL_CROSS_SCHEMAS | AFFINITY_COMPACT_SCHEMAS
