model:
  _yaml_: "model/kfold-edm.yaml"
  protein_sequence_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/prot_seq_3b-upd.pth
  rna_sequence_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/rna_seq_300m.pth
  protein_structure_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/prot_struct_3b.pth
  trunk:
    num_main_blocks: 24
    blocks_per_ckpt: 6
  score_model:
    blocks_per_ckpt: null

train:
  _yaml_: "train-ablation/stage_1.yaml"
  name: edm-mini

  loss:
    diffusion_loss:
      smooth_lddt_loss:
        chunk_size: 12
