_yaml_: "model/kfold-ecsi.yaml"
sequence_encoder:
  path: /mnt/parallel_storage/share/plm_weights/esm-multimodal/esm-multimodal-v1.pt
structure_encoder:
  path: /mnt/parallel_storage/share/plm_weights/unitok/unitok-dips.pt
trunk:
  channel_seq_emb: 1152
  channel_seq_attn: 648
  channel_struct_emb: 1536
  plm_module:
    use_qk_norm: true
  pairformer:
    use_qk_norm: true
  num_register_tokens: 8

structure_module:
  # high-priority parameters
  sampling_schedule_global_u_power: 2.0
  sampling_schedule_churn_fraction: 0.35
  sampling_schedule_ode_fraction: 0.20
  # low-priority parameters
  sampling_schedule_churn_power: 1.40
  sampling_schedule_middle_power: 1.0
  sampling_schedule_ode_power: 2.6
