_yaml_: "model/kfold-ecsi.yaml"
sequence_encoder:
  path: /mnt/parallel_storage/share/plm_weights/esm-multimodal/esm-multimodal-v1.pt
structure_encoder:
  path: /mnt/parallel_storage/share/plm_weights/unitok/unitok-dips.pt
trunk:
  channel_seq_emb: 1152
  channel_seq_attn: 648
  channel_struct_emb: 1536
  plm_module:
    use_qk_norm: true
  pairformer:
    use_qk_norm: true
  num_register_tokens: 8
