# === Model Configuration === #
channel_s: 384
channel_z: 128
dropout: 0.25
diffusion_type: ecsi

input_embedder:
  channel_s: 384
  channel_z: 128
  channel_atom: 128
  channel_atompair: 16
  atom_encoder_blocks: 3
  atom_encoder_heads: 4
  ckpt_atom_stack: false

apo_module:
  channel_apo: 64
  channel_z: 128
  num_blocks: 2
  num_tri_heads: 4
  dropout: 0.1
  num_distogram_bins: 39
  min_dist: 3.25
  max_dist: 50.75
  blocks_per_ckpt: null

protein_sequence_encoder:
  cache_dir: null
  vocab_size: 64
  d_model: 2304
  n_heads: 36
  n_layers: 48

protein_structure_encoder:
  cache_dir: null
  d_model: 2560
  n_heads: 40
  n_layers: 33

rna_sequence_encoder:
  cache_dir: null
  vocab_size: 64
  d_model: 960
  n_heads: 15
  n_layers: 30
  use_moe: true

trunk:
  num_lm_blocks: 2
  num_main_blocks: 24
  num_refine_blocks: 2
  dropout: 0.25
  blocks_per_ckpt: null

parcae:
  state_init: trunc_normal
  decay_init: 0.4472135954999579

score_model:
  channel_a: 768
  channel_s: 384
  channel_z: 128
  channel_atom: 128
  channel_atompair: 16
  channel_coords: 6
  separate_endpoint_atom_encoder: true
  endpoint_branch_dropout: 0.0
  atom_encoder_blocks: 3
  atom_encoder_heads: 4
  token_transformer_blocks: 12
  token_transformer_heads: 12
  atom_decoder_blocks: 3
  atom_decoder_heads: 4
  blocks_per_ckpt: null
  ckpt_atom_stack: false

diffusion_head:
  # ECSI preconditioning
  sigma_data: 16.0
  sigma_data_end: 27.0
  cov_xy: 175.0

  # ECSI coefficients
  time_min: 1e-8
  time_max: 0.9999
  gamma_max: 24.0
  gamma_power: 1.0
  eta: 1.0

  # Inference time schedule
  align_x_0_hat_to_x_t: true
  sampler_mode: sde
  sampler_ode_type: ecsi
  sampler_step_scale: 1.0
  sampler_switch_time: 0.1
  sampler_sde_atom_classes: [all]
  churn_factor: 0.1
  churn_max_multiplier: 4.0
  churn_end_time: 0.5
  churn_max_time: null
  churn_step_fraction: 0.4
  churn_step_power: 1.0
  ode_step_power: 2.0
  stepwarp_power: 0.5

  # Training time schedule
  train_time_schedule: logistic
  train_time_schedule_params: [-2.15, 2.25]
  train_x_0_perturb_time_min: 0.7
  train_x_0_perturb_prob: 0.0
  train_x_0_perturb_translation_std: 4.0

distogram_head:
  channel_z: 128
  num_bins: 64
  min_dist: 2.0
  max_dist: 22.0

confidence_head:
  channel_s: 384
  channel_z: 128
  num_heads_attn: 16
  num_blocks: 4
  dropout: 0.25
  num_bins: 39
  min_dist: 3.25
  max_dist: 50.75
  min_pae_dist: 0.0
  max_pae_dist: 32.0
  num_pae_bins: 64
  min_pde_dist: 0.0
  max_pde_dist: 32.0
  num_pde_bins: 64
  num_plddt_bins: 50
  blocks_per_ckpt: null

patch_pair_geometry: null

# Training preconditioning
diffusion_conditioning_drop_rate: 0.2
confidence_conditioning_drop_rate: 0.2
