_yaml_: "train-ecsi-3.yaml"

model:
  structure_module:
    sampling_schedule_churn_power: 1.30
    churn_factor: 2.75
    ode_time_duration: 0.30
    sampling_schedule_ode_fraction: 0.20

train:
  name: ecsi_cp130_cf275_od030_of020
