model:
  _yaml_: "model/af3.yaml"

train:
  _yaml_: "train/structure_only.yaml"

  name: debug-512
  out_dir: ./experiments/
  seed: 42

  global_hparams:
    max_chains: 20
    max_tokens: 384
    batch_size: 2
    diffusion_batch_size: 48
    global_batch_size: 256
    num_global_steps_per_epoch: 1000

  # pytorch lightning trainer hparams
  trainer:
    strategy: "auto"
    devices: "auto"
    num_nodes: 1
    precision: bf16-mixed

  data:
    lmdb_path: /cache/wykim_lab/kfold_data/kfold_rcsb_processed_v251120.lmdb/
    manifest_path: /cache/wykim_lab/kfold_data/manifests/af3_manifest.pkl
    split_path: ./assets/splits/boltz1
    symmetry_path: /cache/wykim_lab/kfold_data/symmetry.pkl
    num_workers: 4

    cropper:
      max_anchors: 1 # Same to AF-M/AF3 cropping
      w_contiguous: 0.2
      w_spatial: 0.4
      w_spatial_interface: 0.4

  wandb:
    use: false
    project: "KFold-edm"
    group: structure-only # set your group name
    entity: K-Fold # set your entity name
