model:
  _yaml_: "model/kfold-prime-ecsi.yaml"
  sequence_encoder:
    path: /mnt/parallel_storage/share/plm_weights/esm/esm-seo-v2.pt
  trunk:
    channel_seq_emb: 1152
    channel_seq_attn: 648
    plm_module:
      use_qk_norm: true
      blocks_per_ckpt: 4
    pairformer:
      num_blocks: 12
      use_qk_norm: true
      blocks_per_ckpt: 12
    num_register_tokens: 8
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 8
    atom_decoder_blocks: 1
    blocks_per_ckpt: 8

train:
  _yaml_: "train/stage_1.yaml"
  name: ecsi-prime-mini
  out_dir: ./experiments/

  global_hparams:
    batch_size: 4
    global_batch_size: 128

  data:
    max_tokens: 376
    ccd_path: /cache/wykim_lab/kfold_data/v260227/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/rcsb-train/

    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/rcsb-val/

  wandb:
    use: false
    project: "KFold"
    group: ecsi # set your group name
    entity: K-Fold # set your entity name
