model:
  _yaml_: "model/kfold-ecsi.yaml"
  protein_sequence_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/prot_seq_3b.pth
  rna_sequence_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/rna_seq_300m.pth
  protein_structure_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/prot_struct_3b.pth
  trunk:
    plm_module:
      num_blocks: 1
    pairformer:
      num_blocks: 4
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 4
    atom_decoder_blocks: 1
  confidence_head:
    num_blocks: 1

train:
  _yaml_: "train/stage_1.yaml"
  name: ecsi-debug

  loss:
    diffusion_loss:
      smooth_lddt_loss:
        chunk_size: 6
