_yaml_: "train-ecsi-3.yaml"

model:
  structure_module:
    sampling_schedule_churn_power: 1.40
    churn_factor: 3.0
    ode_time_duration: 0.45
    sampling_schedule_ode_fraction: 0.30

train:
  name: ecsi_cp140_cf30_od045_of030
