model:
  _yaml_: "model/kfold-edm.yaml"
  sequence_encoder:
    path: /mnt/parallel_storage/share/plm_weights/esm-multimodal/esm-multimodal-v1.pt
  structure_encoder:
    path: /mnt/parallel_storage/share/plm_weights/unitok/unitok-dips.pt
  trunk:
    channel_seq_emb: 1152
    channel_seq_attn: 648
    channel_struct_emb: 1536
    plm_module:
      use_qk_norm: true
      blocks_per_ckpt: 4
    pairformer:
      use_qk_norm: true
      blocks_per_ckpt: 24
    num_register_tokens: 8
  score_model:
    blocks_per_ckpt: null

train:
  _yaml_: "train/stage_1.yaml"
  name: edm
  out_dir: ./experiments/

  loss:
    diffusion_loss:
      smooth_lddt_loss:
        chunk_size: 8

  data:
    max_tokens: 376
    ccd_path: /cache/wykim_lab/kfold_data/v260310/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        weight: 0.500
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/rcsb-train/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

      - _yaml_: "dataset/afdb-long.yaml"
        weight: 0.415
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/afdb-long/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

      - _yaml_: "dataset/afdb-short.yaml"
        weight: 0.005
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/afdb-short/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

      - _yaml_: "dataset/sair.yaml"
        weight: 0.030
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/SAIR/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

      - _yaml_: "dataset/humap.yaml"
        weight: 0.030
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/huMAP/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

      - _yaml_: "dataset/natural_ab.yaml"
        weight: 0.010
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/NatAb/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

      - _yaml_: "dataset/encore.yaml"
        weight: 0.005
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/ENCORE/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

      - _yaml_: "dataset/protac_db.yaml"
        weight: 0.0045
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/PROTAC-DB/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

      - _yaml_: "dataset/molglue_db.yaml"
        weight: 0.0005
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/MolGlueDB/
        prior_sampler: null
        apo_init:
          use_residue_permutation: false

    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/rcsb-val/
        prior_sampler: null

  wandb:
    use: false
    project: "KFold-Combined"
    group: edm
    entity: K-Fold # set your entity name
