model:
  _yaml_: "model/kfold-expanded-ecsi.yaml"
  sequence_encoder:
    path: /mnt/parallel_storage/share/plm_weights/esm-multimodal/esm-multimodal-v1.pt
  structure_encoder:
    path: /mnt/parallel_storage/share/plm_weights/unitok/unitok-dips.pt
  trunk:
    channel_seq_emb: 1152
    channel_seq_attn: 648
    channel_struct_emb: 1536
    plm_module:
      use_qk_norm: true
      blocks_per_ckpt: 4
    pairformer:
      num_blocks: 16
      use_qk_norm: true
      blocks_per_ckpt: 16
    num_register_tokens: 8
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 8
    atom_decoder_blocks: 1
    blocks_per_ckpt: 8

train:
  _yaml_: "train/stage_1.yaml"
  name: expanded-ecsi-mini
  out_dir: ./experiments/

  global_hparams:
    batch_size: 4
    global_batch_size: 128

  data:
    max_tokens: 376
    ccd_path: /cache/wykim_lab/kfold_data/v260310/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/rcsb-train/

    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/rcsb-val/

  wandb:
    use: false
    project: "KFold"
    group: expanded-ecsi
    entity: K-Fold
