model:
  _yaml_: "model/kfold-ecsi-pairmixer.yaml"
  input_embedder:
    channel_seq_encoder: 2560
    use_apo: true
  trunk:
    num_blocks: 16
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 8
    atom_decoder_blocks: 1

train:
  _yaml_: "train/structure_only.yaml"

  name: mini-esm2-rbf-ddbm
  out_dir: ./experiments/
  seed: 42

  global_hparams:
    max_chains: 20
    max_tokens: 384
    batch_size: 8
    diffusion_batch_size: 48
    global_batch_size: 128
    num_global_steps_per_epoch: 1000

  # pytorch lightning trainer hparams
  trainer:
    strategy: "auto"
    devices: "auto"
    num_nodes: 1
    precision: bf16-mixed

  # Train loss binned logging
  training:
    log_time_binned_losses: true
    time_bin_width: 0.1
    log_entity_binned_losses: true

  data:
    ccd_path: /cache/wykim_lab/kfold_data/v260129/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260129/dataset/rcsb-train/
        apo_init:
          fill_missing_atom: true
    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260129/dataset/rcsb-val/
        apo_init:
          fill_missing_atom: true
    pretrained_embedding:
      seq: esm2-3b
      seq_dim: 2560
      struct: null
      struct_dim: null
      max_struct_ensembles: 1

  wandb:
    use: false
    project: "DDBM"
    group: ddbm # set your group name
    entity: K-Fold # set your entity name
