model:
  _yaml_: "model/kfold-ecsi-nci.yaml"
  trunk:
    plm_module:
      channel_plm_input: 2560
      num_blocks: 4
    pairformer:
      num_blocks: 16
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 8
    atom_decoder_blocks: 1

train:
  _yaml_: "train/stage_1.yaml"

  name: ecsi-mini-esm2-nci
  out_dir: ./experiments/

  global_hparams:
    batch_size: 4
    global_batch_size: 128
    num_global_steps_per_epoch: 1000

  training:
    train_interaction_head: true

  data:
    ccd_path: /cache/wykim_lab/kfold_data/v260130/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260130/dataset/rcsb-train/
    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260130/dataset/rcsb-val/
    pretrained_embedding:
      seq: esm2-3b
      seq_dim: 2560
      struct: null
      struct_dim: null
      max_struct_ensembles: 1

  wandb:
    use: false
    project: "DDBM"
    group: ddbm # set your group name
    entity: K-Fold # set your entity name
