model:
  _yaml_: "model/kfold-edm.yaml"
  input_embedder:
    channel_seq_encoder: 2560

train:
  _yaml_: "train/structure_only.yaml"

  name: base-esm2-rbf-edm
  out_dir: ./experiments/
  seed: 42

  global_hparams:
    max_chains: 20
    max_tokens: 384
    batch_size: 4
    diffusion_batch_size: 48
    global_batch_size: 256
    num_global_steps_per_epoch: 1000

  # pytorch lightning trainer hparams
  trainer:
    strategy: "auto"
    devices: "auto"
    num_nodes: 1
    precision: bf16-mixed

  data:
    ccd_path: /cache/wykim_lab/kfold_data/v260130/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260130/dataset/rcsb-train/
        apo_init:
          fill_missing_atom: false
          prior_sampler:
            type: null
    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260130/dataset/rcsb-val/
        apo_init:
          fill_missing_atom: false
          prior_sampler:
            type: null
    pretrained_embedding:
      seq: esm2-3b
      seq_dim: 2560
      struct: null
      struct_dim: null
      max_struct_ensembles: 1

  wandb:
    use: false
    project: "KFold-Combined"
    group: esm # set your group name
    entity: K-Fold # set your entity name
