model:
  _yaml_: "model/kfold-ecsi.yaml"
  sequence_encoder:
    path: /mnt/parallel_storage/share/plm_weights/esm-multimodal/esm-multimodal-v1.pt
  structure_encoder:
    path: /mnt/parallel_storage/share/plm_weights/unitok/unitok-dips.pt
  trunk:
    plm_module:
      num_blocks: 1
    pairformer:
      num_blocks: 4
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 4
    atom_decoder_blocks: 1
  confidence_head:
    num_blocks: 1

train:
  _yaml_: "train/stage_1.yaml"
  name: ecsi-debug

  loss:
    diffusion_loss:
      smooth_lddt_loss:
        chunk_size: 6
