model:
  _yaml_: "model/af3.yaml"
  trunk:
    use_cuequiv_kernels: true
  structure_module:
    synchronize_sigmas: true

train:
  _yaml_: "train/structure_only.yaml"

  name: debug-512
  out_dir: ./experiments/
  seed: 42

  # pytorch lightning trainer hparams
  trainer:
    strategy: "auto"
    devices: "auto"
    num_nodes: 1
    precision: bf16-mixed
    max_epochs: 100
    limit_train_batches: 1000
    accumulate_grad_batches: 8 # 256 // batch_size // num_gpus

  training:
    diffusion_batch_size: 16
    loss:
      diffusion_loss:
        mse_loss:
          scale: true

  data:
    train_batch_size: 4
    max_tokens: 512
    lmdb_path: /cache/wykim_lab/kfold_data1/kfold_rcsb_processed_v251120.lmdb/
    manifest_path: /cache/wykim_lab/kfold_data1/manifests/all_manifest.pkl
    split_path: ./assets/splits/boltz1
    num_workers: 4

    featurization_args:
      synchronize_ref_pos_augmentation: true

  wandb:
    use: false
    project: "Boltz1"
    group: seonghwanseo # set your group name
    entity: K-Fold # set your entity name
