model:
  _yaml_: "model/kfold-edm.yaml"
  protein_sequence_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/prot_seq_3b.pth
  rna_sequence_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/rna_seq_300m.pth
  protein_structure_encoder:
    path: /mnt/parallel_storage/share/kfold_weights/pretrained/prot_struct_3b.pth
  trunk:
    plm_module:
      blocks_per_ckpt: null
    pairformer:
      num_blocks: 16
      blocks_per_ckpt: 4
  score_model:
    blocks_per_ckpt: 24
  confidence_head:
    num_blocks: 2
    blocks_per_ckpt: null

train:
  _yaml_: "train/stage_1.yaml"
  name: edm-mini

  loss:
    diffusion_loss:
      smooth_lddt_loss:
        chunk_size: 8
