model:
  _yaml_: "model/kfold-ecsi.yaml"
  input_embedder:
    channel_seq_encoder: 2560
    use_apo: true
  trunk:
    use_ensemble: false
    ensemble_module:
      channel_struct_input: null
      num_blocks: 2
    interformer:
      num_blocks: 16
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 8
    atom_decoder_blocks: 1

train:
  _yaml_: "train/structure_only.yaml"

  name: mini-esm2-rbf-ecsi
  out_dir: ./experiments/
  seed: 42

  global_hparams:
    max_chains: 20
    max_tokens: 384
    batch_size: 8
    diffusion_batch_size: 48
    global_batch_size: 128
    num_global_steps_per_epoch: 1000

  # pytorch lightning trainer hparams
  trainer:
    strategy: "auto"
    devices: "auto"
    num_nodes: 1
    precision: bf16-mixed

  data:
    ccd_path: /cache/wykim_lab/kfold_data/v260129/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260129/dataset/rcsb-train/
        manifest_path: /mnt/parallel_storage/wykim_lab/icl_shwan/data/manifests/v260110/all/rcsb-train.json
        apo_init:
          translation_scale: 1.0
    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260129/dataset/rcsb-val/
        manifest_path: /mnt/parallel_storage/wykim_lab/icl_shwan/data/manifests/v260110/all/rcsb-val.json
        apo_init:
          translation_scale: 1.0
    pretrained_embedding:
      seq: esm2-3b
      seq_dim: 2560
      struct: null
      struct_dim: null
      max_struct_ensembles: 1

  wandb:
    use: false
    project: "DDBM"
    group: ddbm # set your group name
    entity: K-Fold # set your entity name
