model:
  _yaml_: "model/af3.yaml"
  trunk:
    num_blocks: 8
    blocks_per_ckpt: 4
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 8
    atom_decoder_blocks: 1
    blocks_per_ckpt: null

train:
  _yaml_: "train/stage_1.yaml"
  name: af3-tiny
  out_dir: ./experiments/

  global_hparams:
    batch_size: 4
    global_batch_size: 128

  data:
    ccd_path: /cache/wykim_lab/kfold_data/v260305/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260305/dataset/rcsb-train/
        apo_init:
          protein_perturbation: null
          ligand_perturbation: null
        prior_sampler: null

    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260305/dataset/rcsb-val/
        prior_sampler: null

  wandb:
    use: false
    project: "AF3"
    group: af3 # set your group name
    entity: K-Fold # set your entity name
