_yaml_: "train-ecsi-mini.yaml"
train:
  data:
    num_workers: 1
    train_datasets:
      # - _yaml_: "./dataset/rcsb-train.yaml"
      #   name: rcsb
      #   data_path: /cache/wykim_lab/kfold_data/v260310/dataset/rcsb-train/
      - _yaml_: "./dataset/afdb-long.yaml"
        name: afdb-long
        data_path: /cache/wykim_lab/kfold_data/v260310/dataset/afdb-long/
