model:
  _yaml_: "model/af3.yaml"
  trunk:
    use_cuequiv_kernels: true

train:
  _yaml_: "train/structure_only.yaml"

  name: debug-512
  out_dir: ./experiments/
  seed: 42

  # pytorch lightning trainer hparams
  trainer:
    strategy: 'auto'
    devices: 'auto'
    num_nodes: 1
    precision: bf16-mixed
    max_epochs: 100
    limit_train_batches: 1000
    accumulate_grad_batches: 16 # 256 // batch_size // num_gpus

  training:
    diffusion_batch_size: 48

  data:
    train_batch_size: 2
    max_tokens: 512
    lmdb_path: /cache/wykim_lab/kfold-data/kfold_rcsb_processed_v251116.lmdb/
    manifest_path: /cache/wykim_lab/kfold-data/manifests/af3_manifest.pkl
    split_path: ./assets/splits/boltz1
    num_workers: 8 # set to batch_size * 4.

  wandb:
    use: false
    project: "KFold-edm"
    group: structure-only # set your group name
    entity: K-Fold # set your entity name
