model:
  _yaml_: "model/kfold-ecsi.yaml"
  sequence_encoder:
    path: /mnt/parallel_storage/share/plm_weights/esm-multimodal/esm-multimodal-v1.pt
  structure_encoder:
    path: /mnt/parallel_storage/share/plm_weights/unitok/unitok-dips.pt
  trunk:
    channel_seq_emb: 1152
    channel_seq_attn: 648
    channel_struct_emb: 1536
    plm_module:
      use_qk_norm: true
      blocks_per_ckpt: 4
    pairformer:
      use_qk_norm: true
      blocks_per_ckpt: 12
    num_register_tokens: 8
  score_model:
    blocks_per_ckpt: null

train:
  _yaml_: "train/stage_2.yaml"
  name: ecsi

  data:
    max_tokens: 632
