model:
  _yaml_: "model/kfold-edm.yaml"
  sequence_encoder:
    path: /mnt/parallel_storage/share/plm_weights/esm-multimodal/esm-multimodal-v1.pt
  structure_encoder:
    path: /mnt/parallel_storage/share/plm_weights/unitok/unitok-dips.pt
  trunk:
    plm_module:
      blocks_per_ckpt: null
    pairformer:
      num_blocks: 16
      blocks_per_ckpt: 4
  score_model:
    blocks_per_ckpt: 24

train:
  _yaml_: "train/stage_1.yaml"
  name: edm-mini

  loss:
    diffusion_loss:
      smooth_lddt_loss:
        chunk_size: 16
