model:
  _yaml_: "model/boltz1-trunk-ddbm.yaml"
  trunk:
    use_cuequiv_kernels: true

train:
  _yaml_: "train/structure_only.yaml"

  name: boltz1-ddbm
  out_dir: ./experiments/
  seed: 42

  global_hparams:
    max_tokens: 512
    batch_size: 2
    diffusion_batch_size: 16
    global_batch_size: 128
    num_global_steps_per_epoch: 250

  # pytorch lightning trainer hparams
  trainer:
    strategy: "auto"
    devices: "auto"
    num_nodes: 1
    precision: 32

  training:
    train_trunk: false
    train_distogram_head: false
    train_structure_module: true
    train_confidence_head: false

  data:
    lmdb_path: /cache/wykim_lab/kfold_data/kfold_rcsb_processed_v251120.lmdb/
    manifest_path: /cache/wykim_lab/kfold_data/manifests/af3_manifest.pkl
    symmetry_path: /cache/wykim_lab/kfold_data/symmetry.pkl
    split_path: ./assets/splits/boltz1
    num_workers: 4

    featurization_args:
      # NOTE: Set true to use pre-trained Boltz1 trunk
      synchronize_ref_pos_augmentation: true

  wandb:
    use: false
    project: "KFold-boltz1-trunk"
    group: ddbm-score-model-only
    entity: K-Fold
