model:
  _yaml_: "model/kfold-ecsi.yaml"
  trunk:
    use_seq_embedding: true
    use_struct_embedding: false
    plm_module:
      channel_plm_input: 1152
    pairformer:
      num_blocks: 16
  score_model:
    atom_encoder_blocks: 1
    token_transformer_blocks: 8
    atom_decoder_blocks: 1

train:
  _yaml_: "train/stage_1.yaml"

  name: ecsi-mini
  out_dir: ./experiments/

  global_hparams:
    batch_size: 4
    global_batch_size: 128
    num_global_steps_per_epoch: 1000

  data:
    ccd_path: /cache/wykim_lab/kfold_data/v260216/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260216/dataset/rcsb-train/
        prior_sampler:
          num_samples: 4
    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260216/dataset/rcsb-val/
        prior_sampler:
          num_samples: 5

    pretrained_embedding:
      seq: esm-seo-v1
      seq_dim: 1152
      struct: null
      struct_dim: null

  wandb:
    use: false
    project: "DDBM"
    group: ddbm # set your group name
    entity: K-Fold # set your entity name
