model:
  _yaml_: "model/kfold-prime-edm.yaml"
  sequence_encoder:
    path: <path-to-esm-model>
  trunk:
    plm_module:
      channel_plm_input: 1152
    blocks_per_ckpt: 16
  score_model:
    blocks_per_ckpt: null

train:
  _yaml_: "train/stage_1.yaml"
  name: edm-prime-large
  out_dir: ./experiments/

  global_hparams:
    batch_size: 1
    max_tokens: 376
    global_batch_size: 256

  data:
    ccd_path: /cache/wykim_lab/kfold_data/v260227/ccd-train.pkl
    train_datasets:
      - _yaml_: "dataset/rcsb-train.yaml"
        weight: 0.5
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/rcsb-train/
        prior_sampler: null

      - _yaml_: "dataset/afdb.yaml"
        weight: 0.35
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/afdb-long/
        prior_sampler: null

      - _yaml_: "dataset/afdb.yaml"
        weight: 0.05
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/afdb-short/
        prior_sampler: null

      - _yaml_: "dataset/humap.yaml"
        weight: 0.06
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/huMAP/
        prior_sampler: null

      - _yaml_: "dataset/natural_ab.yaml"
        weight: 0.03
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/NatAb/
        prior_sampler: null

      - _yaml_: "dataset/encore.yaml"
        weight: 0.01
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/ENCORE/
        prior_sampler: null

    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        data_path: /cache/wykim_lab/kfold_data/v260227/dataset/rcsb-val/
        prior_sampler: null

  wandb:
    use: false
    project: "KFold-Combined"
    group: edm
    entity: K-Fold # set your entity name
