model:
  _yaml_: "model/boltz1-ddbm.yaml"
  trunk:
    use_cuequiv_kernels: false

train:
  _yaml_: "train/train_pdbbind.yaml"

  name: boltz1-ddbm-pdbbind
  out_dir: ./experiments/
  seed: 42

  # pytorch lightning trainer hparams
  trainer:
    strategy: "auto"
    devices: "auto"
    num_nodes: 1
    precision: 32
    max_epochs: 100
    limit_train_batches: 1000
    limit_val_batches: 0 # No validation for now.
    accumulate_grad_batches: 16 # 256 // batch_size // num_gpus

  training:
    diffusion_batch_size: 48

    train_trunk: false
    train_distogram_head: false
    train_structure_module: true
    train_confidence_head: false

  data:
    train_batch_size: 2
    max_tokens: 512
    lmdb_path: /cache/wykim_lab/kfold_data/kfold_rcsb_processed_v251120.lmdb/
    manifest_path: /mnt/parallel_storage/wykim_lab/icl_shwan/data/manifests/pdbbind_pl_manifest.pkl
    split_path: ./assets/splits/equibind/
    num_workers: 8 # set to batch_size * 4.

  wandb:
    use: false
    project: "KFold-boltz1-trunk"
    group: ddbm-score-model-only
    entity: K-Fold
