"""Create deterministic DNA apo files for RCSB preprocessing."""

import argparse
import pathlib

import numpy as np
import zstandard as zstd
from tqdm import tqdm

import kfold.constants as C
from kfold.data.utils.dna_utils import build_dna_single_helix
from kfold.data.utils.io.fasta import read_fasta


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data_dir",
        type=pathlib.Path,
        required=True,
        help="Path to dataset working directory.",
    )
    parser.add_argument(
        "--split",
        required=True,
        type=str,
        choices=["train", "val", "test"],
        help="Data split to process (train/val/test).",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing DNA apo files.",
    )
    parser.add_argument(
        "--format",
        choices=["pdb", "npz", "both"],
        default="pdb",
        help="Output format for DNA apo records.",
    )
    parser.add_argument(
        "--source_dir",
        default="dna",
        help="Apo source directory name under rcsb-{split}/apo.",
    )
    parser.add_argument(
        "--no_zstd",
        action="store_true",
        help="Write plain PDB instead of PDB compressed with zstd.",
    )
    return parser.parse_args()


def normalize_dna_sequence(sequence: str) -> str:
    sequence = "".join(sequence.split()).upper()
    invalid = sorted(set(sequence) - C.residue.DNA_BASES_SET)
    if invalid:
        raise ValueError(f"Unsupported DNA base(s): {', '.join(invalid)}")
    return sequence


def get_dna_residue_names(sequence: str) -> list[str]:
    sequence = normalize_dna_sequence(sequence)
    return [
        C.residue.dna_one_letter_to_residue_name.get(base, C.ResidueName.DN).name
        for base in sequence
    ]


def dna_sequence_to_flat_coords(
    sequence: str,
) -> tuple[list[str], list[list[str]], np.ndarray]:
    """Build deterministic DNA helix coordinates in residue atom order."""
    residue_names = get_dna_residue_names(sequence)
    atom_names_by_residue = [
        [atom.value for atom in C.atom.RESIDUE_ATOMS[C.ResidueName[res_name]]]
        for res_name in residue_names
    ]
    flat_coords = build_dna_single_helix(
        atom_names_by_residue,
        residue_names=residue_names,
    )
    return residue_names, atom_names_by_residue, flat_coords


def dna_sequence_to_atom29(sequence: str) -> np.ndarray:
    """Build deterministic DNA helix coordinates in atom29 representation."""
    sequence = normalize_dna_sequence(sequence)
    _, atom_names_by_residue, flat_coords = dna_sequence_to_flat_coords(sequence)

    coords = np.full((len(sequence), 29, 3), np.nan, dtype=np.float32)
    atom29_order = C.atom.nucleic_acid_atom29_order
    flat_i = 0
    for res_i, atom_names in enumerate(atom_names_by_residue):
        for atom_name in atom_names:
            atom29_i = atom29_order.get(atom_name)
            if atom29_i is not None:
                coords[res_i, atom29_i] = flat_coords[flat_i]
            flat_i += 1
    return coords


def save_dna_apo(path: pathlib.Path, sequence: str, coords: np.ndarray) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    seq_arr = np.array(list(sequence), dtype=np.dtype("S1"))
    np.savez_compressed(path, seq=seq_arr, coords=coords)


def infer_element(atom_name: str) -> str:
    for char in atom_name:
        if char.isalpha():
            return char.upper()
    return ""


def format_dna_pdb(
    residue_names: list[str],
    atom_names_by_residue: list[list[str]],
    flat_coords: np.ndarray,
) -> str:
    lines = [
        "REMARK Generated by scripts/process/rcsb/f2b_create_dna_apo.py\n",
        "REMARK Heuristic right-handed single-stranded DNA helix\n",
    ]
    serial = 1
    coord_i = 0
    for res_i, (res_name, atom_names) in enumerate(
        zip(residue_names, atom_names_by_residue, strict=True),
        start=1,
    ):
        for atom_name in atom_names:
            x, y, z = flat_coords[coord_i]
            element = infer_element(atom_name)
            lines.append(
                f"ATOM  {serial:5d} {atom_name:^4s} {res_name:>3s} "
                f"A{res_i:4d}    "
                f"{x:8.3f}{y:8.3f}{z:8.3f}"
                f"{1.00:6.2f}{0.00:6.2f}          {element:>2s}\n"
            )
            serial += 1
            coord_i += 1
    lines.append("TER\nEND\n")
    return "".join(lines)


def save_dna_pdb(
    path: pathlib.Path,
    residue_names: list[str],
    atom_names_by_residue: list[list[str]],
    flat_coords: np.ndarray,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pdb_text = format_dna_pdb(residue_names, atom_names_by_residue, flat_coords)
    if path.name.endswith(".zst"):
        compressor = zstd.ZstdCompressor()
        path.write_bytes(compressor.compress(pdb_text.encode("utf-8")))
    else:
        path.write_text(pdb_text)


def main() -> None:
    args = parse_args()
    data_dir: pathlib.Path = args.data_dir / f"rcsb-{args.split}"
    seq_path = data_dir / "sequences" / "unique_dna_sequences.fasta"
    out_dir = data_dir / "apo" / args.source_dir

    if not seq_path.exists():
        raise FileNotFoundError(f"DNA sequence FASTA not found: {seq_path}")

    sequences = read_fasta(seq_path)
    print(f"Creating DNA apo structures for {len(sequences)} unique sequences.")
    out_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    skipped = 0
    for seq_id, sequence in tqdm(sequences, desc="Creating DNA apo"):
        pdb_suffix = ".pdb" if args.no_zstd else ".pdb.zst"
        pdb_path = out_dir / f"{seq_id}{pdb_suffix}"
        npz_path = out_dir / f"{seq_id}.npz"
        out_paths = []
        if args.format in {"pdb", "both"}:
            out_paths.append(pdb_path)
        if args.format in {"npz", "both"}:
            out_paths.append(npz_path)
        if all(path.exists() for path in out_paths) and not args.overwrite:
            skipped += 1
            continue

        sequence = normalize_dna_sequence(sequence)
        residue_names, atom_names_by_residue, flat_coords = dna_sequence_to_flat_coords(
            sequence
        )
        if args.format in {"pdb", "both"}:
            save_dna_pdb(pdb_path, residue_names, atom_names_by_residue, flat_coords)
        if args.format in {"npz", "both"}:
            coords = dna_sequence_to_atom29(sequence)
            save_dna_apo(npz_path, sequence, coords)
        written += 1

    print(f"Finished DNA apo creation. Written: {written}, skipped: {skipped}")
    print(f"Output directory: {out_dir}")


if __name__ == "__main__":
    main()
