# RCSB training dataset configuration.
_yaml_: "default-train.yaml"

name: "rcsb"
type: "rcsb"
prob_use_complex_apo: 0.5
prob_use_complex_prior: 0.5

sampler:
  _registry_: "data_sampler"
  _class_: ClusterSampler
  beta_chain: 0.5
  beta_interface: 1.0
  allow_redundant: False
