model:
  _yaml_: "../kfold.yaml"
  trunk:
    blocks_per_ckpt: 1
  score_model:
    blocks_per_ckpt: 1
    ckpt_atom_stack: true
  confidence_head:
    blocks_per_ckpt: 1

train:
  _yaml_: "full.yaml"
  name: stage2
  seed: 2

  training:
    diffusion_batch_size: 32

  loss:
    weights:
      bond: 1.0

  data:
    max_chains: 20
    max_tokens: 640
    max_atoms: 7680
    max_sequence_tokens: 1280

    ccd_path: /cache/wykim_lab/kfold_data/v260701_af3/ccd-train.pkl
    data_root: /cache/wykim_lab/kfold_data/v260701_af3/dataset/
    train_datasets:
      # RCSB PDB (50%)
      - _yaml_: "dataset/rcsb-train.yaml"
        name: rcsb-train-upd
        weight: 0.500

      # Disordered PDB (1%)
      - _yaml_: "dataset/disordered_pdb.yaml"
        name: disordered_pdb
        weight: 0.010

      # Protein Monomer (30%)
      - _yaml_: "dataset/distill-monomer.yaml"
        name: AF2-MGnify-long
        weight: 0.250
      - _yaml_: "dataset/distill-monomer.yaml"
        name: AF2-MGnify-short
        weight: 0.001
      - _yaml_: "dataset/distill-monomer.yaml"
        name: AFDB-long
        weight: 0.045
      - _yaml_: "dataset/distill-monomer.yaml"
        name: AFDB-short
        weight: 0.004

      # RNA Monomer (2%)
      - _yaml_: "dataset/distill-rna-monomer.yaml"
        name: Rfam
        weight: 0.020

      # Protein-Protein (13%)
      - _yaml_: "dataset/distill-homodimer.yaml"
        name: AFDB-homodimer
        manifest_path: /cache/wykim_lab/kfold_data/v260701_af3/dataset/AFDB-homodimer/manifest_08.msgpack
        weight: 0.100

      - _yaml_: "dataset/distill-heterodimer.yaml"
        name: AFDB-heterodimer
        manifest_path: /cache/wykim_lab/kfold_data/v260701_af3/dataset/AFDB-heterodimer/manifest_08.msgpack
        weight: 0.030

      # Protein-DNA (2%)
      - _yaml_: "dataset/distill-complex-uniform.yaml"
        name: JASPAR
        weight: 0.020
        cropper:
          w_contiguous: 0.2
          w_spatial: 0.0
          w_spatial_interface: 0.8

      # Protein-RNA (1%)
      - _yaml_: "dataset/distill-complex-cluster.yaml"
        name: ENCORE
        weight: 0.010
        cropper:
          w_contiguous: 0.2
          w_spatial: 0.0
          w_spatial_interface: 0.8

      # Protein-ligand, TPD (1%)
      - _yaml_: "dataset/distill-complex-cluster.yaml"
        name: TPD
        manifest_path: /cache/wykim_lab/kfold_data/v260701_af3/dataset/TPD/manifest_filtered.msgpack
        weight: 0.010
        cropper:
          w_contiguous: 0.2
          w_spatial: 0.0
          w_spatial_interface: 0.8

    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        name: rcsb-val
