_yaml_: "structure-only.yaml"

# Training parameters for multi-gpu setup.
global_hparams:
  batch_size: 1
  diffusion_batch_size: 32
  global_batch_size: 256
  num_global_steps_per_epoch: 1000

data:
  max_chains: 20
  max_tokens: 768
  max_sequence_tokens: 1280

loss:
  weights:
    bond: 1.0 # Turn on bond loss (See Section 5.2 for the AF3 paper)
