_yaml_: "full.yaml"

data:
  ccd_path: /cache/wykim_lab/kfold_data/v260526/ccd-train.pkl
  data_root: /cache/wykim_lab/kfold_data/v260526/dataset/
  train_datasets:
    # RCSB PDB (50%)
    - _yaml_: "../dataset/rcsb-train.yaml"
      name: rcsb-train
      weight: 0.500

    # Disordered PDB datasets (2%)
    - _yaml_: "../dataset/disordered_pdb.yaml"
      name: disordered_pdb
      weight: 0.020

    # Protein Monomer (45%)
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AF2-MGnify-long
      weight: 0.399
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AF2-MGnify-short
      weight: 0.001

    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AFDB-long
      weight: 0.046
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AFDB-short
      weight: 0.004

    # RNA Monomer (5%)
    - _yaml_: "../dataset/distill-rna-monomer.yaml"
      name: Rfam
      weight: 0.050

    # Protein-Protein (5.5%)
    - _yaml_: "../dataset/distill-homodimer.yaml"
      name: AFDB-homodimer
      weight: 0.050

    - _yaml_: "../dataset/distill-complex.yaml"
      name: BioGRID
      weight: 0.005

    # Antibody-related (2%)
    - _yaml_: "../dataset/distill-antibody.yaml"
      name: PLAbDab
      weight: 0.0175

    - _yaml_: "../dataset/distill-interface.yaml"
      name: NatAb
      weight: 0.0025

    # Protein-DNA (2%)
    - _yaml_: "../dataset/distill-complex.yaml"
      name: JASPAR
      weight: 0.020

    # Protein-RNA (0.5%)
    - _yaml_: "../dataset/distill-interface.yaml"
      name: ENCORE
      weight: 0.005

    # Protein-ligand, TPD (1%)
    - _yaml_: "../dataset/distill-interface.yaml"
      name: SAIR
      weight: 0.0090

    - _yaml_: "../dataset/distill-interface.yaml"
      name: PROTAC-DB
      weight: 0.0005

    - _yaml_: "../dataset/distill-interface.yaml"
      name: MolGlueDB
      weight: 0.0005

  val_datasets:
    - _yaml_: "../dataset/rcsb-val.yaml"
      name: rcsb-val
      data_path: /cache/wykim_lab/kfold_data/v260522/dataset/rcsb-val/
