_yaml_: "full.yaml"

seed: 2

global_hparams:
  diffusion_batch_size: 32

loss:
  weights:
    bond: 1.0 # Turn on bond loss (See Section 5.2 for the AF3 paper)

data:
  max_chains: 20
  max_tokens: 640
  max_atoms: 7680
  max_sequence_tokens: 1280

  ccd_path: /cache/wykim_lab/kfold_data/v260701_af3/ccd-train.pkl
  data_root: /cache/wykim_lab/kfold_data/v260701_af3/dataset/
  train_datasets:
    # RCSB PDB (50%)
    - _yaml_: "../dataset/rcsb-train-ft.yaml"
      name: rcsb-train
      weight: 0.500

    # Disordered PDB datasets (1%)
    - _yaml_: "../dataset/disordered_pdb.yaml"
      name: disordered_pdb
      weight: 0.010

    # Protein Monomer (30%)
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AF2-MGnify-long
      weight: 0.250
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AF2-MGnify-short
      weight: 0.001

    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AFDB-long
      weight: 0.045
    - _yaml_: "../dataset/distill-monomer.yaml"
      name: AFDB-short
      weight: 0.004

    # RNA Monomer (2%)
    - _yaml_: "../dataset/distill-rna-monomer.yaml"
      name: Rfam
      weight: 0.020

    # Protein-Protein (13%)
    - _yaml_: "../dataset/distill-homodimer.yaml"
      manifest_path: /cache/wykim_lab/kfold_data/v260701_af3/dataset/AFDB-homodimer/manifest_08.msgpack
      name: AFDB-homodimer
      weight: 0.100

    - _yaml_: "../dataset/distill-heterodimer.yaml"
      manifest_path: /cache/wykim_lab/kfold_data/v260701_af3/dataset/AFDB-heterodimer/manifest_08.msgpack
      name: AFDB-heterodimer
      weight: 0.030

    # Protein-DNA (2%)
    - _yaml_: "../dataset/distill-complex.yaml"
      name: JASPAR
      weight: 0.020

    # Protein-RNA (1%)
    - _yaml_: "../dataset/distill-interface.yaml"
      name: ENCORE
      weight: 0.010

    # Protein-ligand, TPD (1%)
    - _yaml_: "../dataset/distill-interface.yaml"
      name: TPD
      weight: 0.010

  val_datasets:
    - _yaml_: "../dataset/rcsb-val.yaml"
      name: rcsb-val
