_yaml_: "stage_0.yaml"

seed: 4

training:
  train_trunk: false
  train_diffusion_head: false
  train_confidence_head: true

optimizer:
  load_opt_state_from_checkpoint: false
  final_training_stage: true

data:
  max_chains: 50
  max_tokens: 768
  max_sequence_tokens: 1280

  train_datasets:
    - _yaml_: "../dataset/rcsb-train-confidence.yaml"
      name: rcsb-train
