model:
  _yaml_: "../kfold.yaml"
  confidence_head:
    blocks_per_ckpt: null

train:
  _yaml_: "full.yaml"
  name: stage4
  seed: 4

  init_from_ema: ['trunk', 'diffusion_head']

  optimizer:
    max_lr: 0.0006
    lr_decay_factor: 1.0

  training:
    train_trunk: false
    train_diffusion_head: false
    train_confidence_head: true
    num_mini_rollout_steps: 50
    num_mini_rollout_samples: 1

  data:
    max_chains: 50
    max_tokens: 768
    max_atoms: 9216
    max_sequence_tokens: 1536

    ccd_path: /cache/wykim_lab/kfold_data/v260701_af3/ccd-train.pkl
    data_root: /cache/wykim_lab/kfold_data/v260701_af3/dataset/
    train_datasets:
      # RCSB PDB (75%)
      - _yaml_: "dataset/rcsb-train.yaml"
        name: rcsb-train-upd
        weight: 1.0
        cropper:
          w_contiguous: 0.2
          w_spatial: 0.4
          w_spatial_interface: 0.4

    val_datasets:
      - _yaml_: "dataset/rcsb-val.yaml"
        name: rcsb-val
