# Configuration for K-Fold structure module training

name: structure-only
out_dir: ./experiments/

# Reproducibility
seed: 42
synchronize_seed: true # Use the same seed across DDP processes

# Training parameters for multi-gpu setup.
global_hparams:
  max_chains: 20
  max_tokens: 384
  batch_size: 1
  diffusion_batch_size: 48
  global_batch_size: 256
  num_global_steps_per_epoch: 1000

data:
  _registry_: "datamodule"
  _class_: TrainingDataModule

  # DataLoader
  train_batch_size: 1 # NOTE: overriden by global_hparam
  val_batch_size: 1
  num_workers: 8
  max_chains: 20 # NOTE: overriden by global_hparam
  max_tokens: 384 # NOTE: overriden by global_hparam
  pin_memory: true
  safe_load: false

  # Data paths
  lmdb_path: <LMDB_PATH_PLACEHOLDER>
  manifest_path: <MANIFEST_PATH_PLACEHOLDER>
  symmetry_path: <SYMMETRY_PATH_PLACEHOLDER>
  split_path: ./assets/splits/boltz1

  # Symmetry
  return_train_symmetry: false
  return_validation_symmetry: true

  # Additional data paths if needed
  paths:
    # Precomputed embeddings
    seq_embedding_path: null
    struct_embedding_path: null

  filters:
    - _registry_: "data_filter"
      _class_: NumChainFilter
      max_chains: 300
    - _registry_: "data_filter"
      _class_: ReleaseDateFilter
      date: "2021-09-30"
      ref: released
    - _registry_: "data_filter"
      _class_: ResolutionFilter
      resolution: 9.0

  cropper:
    _registry_: "data_cropper"
    _class_: MultiAnchorCropper
    max_anchors: 3
    w_contiguous: 0.3
    w_spatial: 0.2
    w_spatial_interface: 0.5

  sampler:
    _registry_: "data_sampler"
    _class_: ClusterSampler
    beta_chain: 0.5
    beta_interface: 1.0
    allow_redundant: False # Different to Boltz1

  # Apo perturbation configurations:
  apo_perturbation_args:
    use_perturbation: false # TODO: set to true after implementation is complete
    use_random_rotation: true
    use_symmetry_correction: true # enabled during training
    prob_perturbation: 0.5
    prob_replace_to_holo: 0.0 # enabled during training
    mask_nucleic_acids: true # TODO: remove this after NA apo structures are available

  # Featurizer configurations:
  featurization_args:
    augment_ref_pos: true
    synchronize_ref_pos_augmentation: false
    # Precomputed embeddings
    # TODO: remove these params if all chains have precomputed embeddings
    seq_embedding_dim: null
    struct_embedding_dim: null

# Lightning Trainer Configuration
trainer:
  accelerator: "auto"
  strategy: "auto"
  devices: "auto"
  num_nodes: "auto"
  precision: bf16-mixed
  max_epochs: -1
  limit_train_batches: 1 # NOTE: overriden by global_hparam
  limit_val_batches: null
  log_every_n_steps: 1
  enable_checkpointing: true
  accumulate_grad_batches: 1 # NOTE: overriden by global_hparam
  gradient_clip_val: 10.0

# Exponential Moving Average (EMA)
training:
  # Training step hyperparameters
  train_trunk: true
  train_distogram_head: true
  train_structure_module: true
  train_confidence_head: false

  num_cycles: 4

  # For structure module training
  diffusion_batch_size: 48 # NOTE: overriden by global_hparam

  # For confidence module training
  num_steps: 20 # Mini-diffusion rollout
  num_diffusion_samples: 1 # Number of diffusion samples for confidence training

validation:
  # Validation step hyperparameters
  num_cycles: 4
  num_steps: 200
  num_diffusion_samples: 5
  symmetry_correction: true
  save_structure_path: null # if given, save structure

optimizer:
  opt: "adam"
  beta_1: 0.9
  beta_2: 0.95
  eps: 1e-8
  lr_scheduler: af3
  base_lr: 0.0
  max_lr: 0.0018
  lr_warmup_no_steps: 1000
  lr_start_decay_after_n_steps: 50000
  lr_decay_every_n_steps: 50000
  lr_decay_factor: 0.95
  use_ema: true
  ema_decay: 0.999

loss:
  weights:
    # global loss weights
    distogram: 3e-2
    diffusion: 4.0
    confidence: 1e-4
    # diffusion loss weights
    smooth_lddt: 1. # 0 for fine-tuning (See Section 5.2 for the AF3 paper)
    bond: 0.0 # 1 for fine-tuning (See Section 5.2 for the AF3 paper)
    # confidence loss weights
    pae: 0.0 # 1 for final stage training

  # Distogram loss
  distogram_loss:
    num_bins: 64
    min_dist: 2.0
    max_dist: 22.0

  # Diffusion loss
  diffusion_loss:
    # Weighted MSE Loss
    mse_loss:
      # NOTE: these are same to AlphaFold3:
      # w = 1 + 5 * is_dna + 5 * is_rna + 10 * is_ligand
      upweight_protein: 0.0
      upweight_dna: 5.0
      upweight_rna: 5.0
      upweight_ligand: 10.0
      scale: false

    # Bond Loss
    bond_loss: {}

    # Smooth LDDT Loss
    smooth_lddt_loss: {}

  # Confidence loss
  # TODO
  confidence_loss: {}

wandb:
  use: false
  project: "KFold"
  group: null # set your group name
  entity: null # set your entity name
